---
apiVersion: v1
kind: Secret
metadata:
  name: blues-man3-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23JanusN/blues-man3-frontend-gitops
